### ISSUE TITLE
Duda proyecto Base

### ISSUE THREAD

**Issue by tadeopalaciosr** [specolombiahackathon/202104#1]

**Comment by specolombiahackathon** [comment]
buenos dias, 
supervisada significa que en el set de datos de entrenamiento ya está definda la categoria  que se quiere predecir.   
no supervisada (o clustering) significa que hay que buscar los patrones que definas la similitud de entre cada observacion. 

![image](https://user-images.githubusercontent.com/73674657/117851052-8e064900-b24b-11eb-969d-20298ae4a4d4.png)
